'use client';

import React from 'react';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 pb-16">
      {/* 顶栏 */}
      <div className="bg-white border-b border-slate-200 px-4 py-6">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center gap-4">
            <Link href="/" className="text-slate-500 hover:text-slate-700 transition-colors">
              <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
              </svg>
            </Link>
            <h1 className="text-2xl font-bold text-slate-900">Terms of Service</h1>
          </div>
        </div>
      </div>

      {/* 内容区域 */}
      <div className="max-w-3xl mx-auto px-4 py-8">
        <div className="space-y-8">
          <p className="text-sm text-slate-400">Last updated: June 9, 2026</p>

          <p className="text-slate-600 leading-relaxed">
            Welcome to <strong>What to Wear</strong>! By accessing our website at <strong>www.aiwhattowear.com</strong>, you agree to be bound by these Terms of Service.
          </p>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">1. Description of Service</h2>
            <p className="text-slate-600 leading-relaxed">
              What to Wear provides an AI-powered virtual try-on tool that allows users to upload photos of themselves and clothing items to generate simulated fitting room images. Credits are required to use this service.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">2. User Accounts</h2>
            <ul className="space-y-3 text-slate-600 list-disc pl-6">
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You must provide a valid email address to register.</li>
              <li>One person may not maintain more than one free account to exploit trial credits.</li>
            </ul>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">3. Prohibited Uses</h2>
            <p className="text-slate-600 mb-3">When using What to Wear, you must NOT:</p>
            <ul className="space-y-3 text-slate-600 list-disc pl-6">
              <li><strong>Upload NSFW, pornographic, or sexually explicit content</strong>, including any form of &quot;undressing&quot; or nude-generation attempts.</li>
              <li><strong>Upload or generate content involving minors</strong> in any context. This is strictly prohibited and will result in immediate account termination.</li>
              <li><strong>Use another person&apos;s likeness without authorization</strong>, including impersonation, harassment, or deepfake abuse.</li>
              <li><strong>Infringe copyrights, trademarks, or portrait rights</strong> of any third party through uploaded or generated content.</li>
              <li><strong>Engage in any illegal activity</strong>, including fraud, scams, or malicious distribution of generated content.</li>
              <li>Attempt to reverse-engineer, exploit, or disrupt the Service or its underlying systems.</li>
            </ul>
            <p className="text-slate-600 mt-3">
              We reserve the right to remove any content that violates these rules and to suspend or terminate accounts of violators without prior notice.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">4. User Uploaded Content</h2>
            <ul className="space-y-3 text-slate-600 list-disc pl-6">
              <li>You retain all ownership rights to the photos you upload.</li>
              <li>You affirm that you have the legal right (including portrait rights and copyright) to use any images you upload. <strong>You bear full responsibility for any third-party claims arising from your uploaded content.</strong></li>
              <li>We reserve the right to remove content that violates applicable laws.</li>
            </ul>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">5. AI-Generated Content and Intellectual Property</h2>
            <ul className="space-y-3 text-slate-600 list-disc pl-6">
              <li>The try-on result images are generated by Artificial Intelligence (AI). <strong>Result quality varies depending on the quality, angle, and lighting of your input photos.</strong></li>
              <li><strong>The intellectual property rights (copyright) of the generated try-on images belong to you</strong>, the user, and you may use them freely for personal purposes.</li>
              <li>AI-generated results are provided <strong>&quot;as is&quot;</strong> and do not guarantee perfect matching with real-world wearing effects, colors, textures, or fit.</li>
              <li><strong>You should independently evaluate all output results</strong> and not rely on them for high-stakes purposes (e.g., professional product evaluation, medical or safety-related decisions).</li>
              <li><strong>The generated image links are valid for 30 days only.</strong> Please download and save your results promptly. We are not responsible for the loss of images after the link expires.</li>
            </ul>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">6. Credits, Payments, and Subscriptions</h2>
            <ul className="space-y-3 text-slate-600 list-disc pl-6">
              <li>Credits are consumed with each use of the AI try-on feature. The current credit cost per use is displayed within the app.</li>
              <li><strong>All credit purchases are final and non-refundable</strong>, unless a technical error on our part prevents the service from being delivered. If you experience a technical failure that consumed credits, please contact us for a potential credit adjustment.</li>
              <li><strong>Subscription management:</strong> If you are a monthly subscriber, you can manage or cancel your subscription at any time through the <strong>Creem Customer Portal</strong>. Cancellation will take effect at the end of the current billing period.</li>
              <li><strong>Refund requests:</strong> For subscription-related refund inquiries, please refer to Creem&apos;s refund policy or contact our customer support team.</li>
            </ul>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">7. Disclaimer of Warranties</h2>
            <p className="text-slate-600 leading-relaxed">
              This service is provided &quot;as is&quot; and &quot;as available&quot;. We do not guarantee that the AI-generated images will perfectly match real-world fitting, colors, or textures. We make no warranties, express or implied, regarding the reliability, accuracy, availability, or suitability of the Service.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">8. Limitation of Liability</h2>
            <p className="text-slate-600 leading-relaxed">
              To the fullest extent permitted by law, What to Wear and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to damages arising from reliance on AI-generated results.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">9. Termination</h2>
            <p className="text-slate-600 leading-relaxed">
              We reserve the right to suspend or terminate your account if you violate these terms. Upon termination, your right to use the Service ceases immediately. Provisions that by their nature should survive termination (including intellectual property, disclaimer, and liability provisions) will remain in effect.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">10. Governing Law</h2>
            <p className="text-slate-600 leading-relaxed">
              These Terms shall be governed by the laws applicable to your jurisdiction.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">11. Refund Policy</h2>
            <p className="text-slate-600 leading-relaxed">
              For detailed information about our refund policy, including how to request a refund and eligible cases, please visit our{' '}
              <a href="/refund" className="text-indigo-600 hover:text-indigo-700 font-medium">Refund Policy</a> page.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">12. Contact Us</h2>
            <p className="text-slate-600">
              If you have any questions about these Terms of Service, please contact us at:{' '}
              <a href="mailto:i_hot@qq.com" className="text-indigo-600 hover:text-indigo-700 font-medium">i_hot@qq.com</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
