'use client';

import React from 'react';
import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-50 pb-16">
      {/* 顶栏 */}
      <div className="bg-white border-b border-slate-200 px-4 py-6">
        <div className="max-w-3xl mx-auto">
          <div className="flex items-center gap-4">
            <Link href="/" className="text-slate-500 hover:text-slate-700 transition-colors">
              <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
              </svg>
            </Link>
            <h1 className="text-2xl font-bold text-slate-900">Terms of Service</h1>
          </div>
        </div>
      </div>

      {/* 内容区域 */}
      <div className="max-w-3xl mx-auto px-4 py-8">
        <div className="space-y-8">
          <p className="text-sm text-slate-400">Last updated: June 8, 2026</p>

          <p className="text-slate-600 leading-relaxed">
            Welcome to <strong>What to Wear</strong>! By accessing our website at <strong>www.aiwhattowear.com</strong>, you agree to be bound by these Terms of Service.
          </p>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">1. Description of Service</h2>
            <p className="text-slate-600 leading-relaxed">
              What to Wear provides an AI-powered virtual try-on tool that allows users to upload photos of themselves and clothing items to generate simulated fitting room images. Credits are required to use this service.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">2. User Accounts</h2>
            <ul className="space-y-3 text-slate-600 list-disc pl-6">
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You must provide a valid email address to register.</li>
              <li>One person may not maintain more than one free account to exploit trial credits.</li>
            </ul>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">3. User Uploaded Content</h2>
            <ul className="space-y-3 text-slate-600 list-disc pl-6">
              <li>You retain all ownership rights to the photos you upload.</li>
              <li>You affirm that you have the legal right (including portrait rights and copyright) to use any images you upload. <strong>You bear full responsibility for any third-party claims arising from your uploaded content.</strong></li>
              <li>We reserve the right to remove content that violates applicable laws.</li>
            </ul>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">4. AI-Generated Content and Intellectual Property</h2>
            <ul className="space-y-3 text-slate-600 list-disc pl-6">
              <li>The try-on result images are generated by Artificial Intelligence (AI).</li>
              <li><strong>The intellectual property rights (copyright) of the generated try-on images belong to you</strong>, the user, and you may use them freely for personal purposes.</li>
              <li>AI-generated results may vary and do not guarantee 100% real-world accuracy.</li>
            </ul>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">5. Credits, Payments, and Refunds</h2>
            <ul className="space-y-3 text-slate-600 list-disc pl-6">
              <li>Credits are consumed with each use of the AI try-on feature. The current credit cost per use is displayed within the app.</li>
              <li><strong>All credit purchases and subscription fees are final and non-refundable</strong>, unless a technical error on our part prevents the service from being delivered. If you experience a technical failure that consumed credits, please contact us for a potential credit adjustment.</li>
            </ul>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">6. Disclaimer of Warranties</h2>
            <p className="text-slate-600 leading-relaxed">
              This service is provided "as is". We do not guarantee that the AI-generated images will perfectly match real-world fitting, colors, or textures.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">7. Termination</h2>
            <p className="text-slate-600 leading-relaxed">
              We reserve the right to suspend or terminate your account if you violate these terms.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">8. Governing Law</h2>
            <p className="text-slate-600 leading-relaxed">
              These Terms shall be governed by the laws applicable to your jurisdiction.
            </p>
          </section>

          <hr className="border-slate-200" />

          <section>
            <h2 className="text-xl font-bold text-slate-900 mb-4">9. Contact Us</h2>
            <p className="text-slate-600">
              If you have any questions about these Terms of Service, please contact us at:{' '}
              <a href="mailto:i_hot@qq.com" className="text-indigo-600 hover:text-indigo-700 font-medium">i_hot@qq.com</a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
